### ISSUE TITLE
From ele

### ISSUE THREAD

**Issue by guettli** [gawel/pyquery#110]
I could not find a way to serialize an element. Maybe it would be good to 
update the docs. Or I was blind and should buy me some new glasses :-)

I want to check if the serialized output of an element matches a fixed string.

For me `etree.tostring(my_div)` looks ugly.

Is there no cleaner way?

Maybe without a second import?

    from lxml import etree
    import pyquery
    
    tree=pyquery.PyQuery('<div id="foo">abc</div>')
    my_div=tree('#foo')[0]
    assert '<div id="foo">abc</div>' == etree.tostring(my_div)

**Comment by gawel** [comment]
use str() or .outerHtml()

**Comment by guettli** [comment]
This snippet
{{{
import pyquery

tree=pyquery.PyQuery('<div id="foo">abc</div>')
my_div=tree('#foo')[0]
assert 0, (str(my_div), unicode(my_div))
}}}

has this output in my case: ('<Element div at 0x7f59224d91b8>', 
u'<Element div at 0x7f59224d91b8>')

Sorry, str() does not work.

**Comment by gawel** [comment]
str(tree('#foo'))

**Comment by guettli** [comment]
the above code is just an example. In my case I have only `my_div`. But I guess I should check the docs of lxml, and not pyquery ...

Thank you for your support.

**Comment by gawel** [comment]
If you need to use the underlying elements then tostring maybe the only option
