### ISSUE TITLE
.text() should exclude <script> tags

### ISSUE THREAD

**Issue by est** [gawel/pyquery#111]
>>> pyquery.PyQuery('<div>hello<script language="javascript">alert(0)</script>, world</div>').text()
    'hello alert(0) , world'

Is this by design? If so, is there a way to get rid of `<script>` tags during `text()` ?

**Comment by est** [comment]
workaround for `lxml` in case anyone needed

    ' '.join(x.text for x in elem.xpath('.//*[not(self::script or self::style)]') if x.text)

**Comment by neumond** [comment]
Why should it exclude scripts? What if I _want_ script tag content? I guess it's better to remove scripts before getting text() in your case:
```
pq('script').remove()
pq.text()
```

**Comment by est** [comment]
@neumond well your reply made me speechless. Hope you enjoy the scripts and style declarations in your text. 

Thanks for the solution though, works well.

**Comment by neumond** [comment]
You probably don't know that jquery's text() method acquires scripts and styles along with normal text.

As far as I know jquery does exclude scripts, but in another case, when you assign innerHTML. It is intended to guarantee some degree of safety. Reexecuting scripts by assigning innerHTML causes hard-to-catch bugs.

**Comment by gawel** [comment]
I agree that be able to retrieve scripts can be usefull. for example to extract some json included in the html (who use apis?)
