### ISSUE TITLE
PyQuery disregards file-encoding. Reads file in as ISO-8859-1, even if file is encoded as UTF-8

### ISSUE THREAD

**Issue by vivin** [gawel/pyquery#113]
I'm not sure if I'm doing something wrong here, since I don't frequently use Python. I have an HTML file that I downloaded and saved to disk. The encoding is UTF-8:
```bash
$ file -i info.html
info.html: text/html; charset=utf-8
```

When I parse the file with PyQuery by passing in a filename, and extract text, I get garbage characters:
```python
>>> d = PyQuery(filename="file.html")
>>> d("span#info").eq(0).text().encode("utf-8")
b'THE\xc3\xa2\xc2\x98\xc2\x85 STAR
```

However, if I read the file into a string and *then* pass it to PyQuery, everything turns out fine:
```python
>>> with open ("file.html", "r") as f:
...     s = f.read()
... 
>>> d = PyQuery(s)
>>> d("span#info").eq(0).text().encode("utf-8")
b'THE\xe2\x98\x85 STAR'
```

The actual text when printed, should be `"THE★STAR"`, but instead I get garbage on the console because it appears that the file has been decoded into ISO-8859-1. If you decode the UTF-8 byte-sequence into ISO-8859-1 and then encode it back into UTF-8, you get the same, garbled sequences of bytes:
```python
>>> b'THE\xe2\x98\x85 STAR'.decode("iso-8859-1").encode("utf-8")
b'THE\xc3\xa2\xc2\x98\xc2\x85 STAR'
```

I'm using the workaround for now, but it seems unnecessary. Is there a configuration option I'm missing?

**Comment by gawel** [comment]
I don't think you're missing something.
but this has nothing to do with pyquery. we use fromstring method from lxml to read a file

https://github.com/gawel/pyquery/blob/master/pyquery/pyquery.py#L201

**Comment by vivin** [comment]
Yeah, I noticed that when I dove into the code. lxml then calls html5lib's `parse` method and sets the `useChardet` flag to `True`. It appears that html5lib guesses the encoding incorrectly when a file is sent in, versus sending in a string. The `parse` method in `html5lib` does support an explicit argument for the encoding, but unfortunately `lxml` doesn't use that. I was going to suggest that it would be nice if you could pass in the encoding to `PyQuery`, but it looks like there's not much you would be able to do with it anyway, since lxml is not going to send it in to html5lib.

**Comment by woxcab** [comment]
If this problem appears using `PyQuery(url=...)` constructor and correct encoding is known then it can be solved by explicit passing `encoding` parameter, e.g. `PyQuery(url=my_url, encoding='utf-8')`.

**Comment by drzraf** [comment]
For those affected by this recurring issue (which always beats me when working on fragments without ``<head>``'s meta [using 1.2.9]):
``
    import lxml.html
    UTF8_PARSER = lxml.html.HTMLParser(encoding='utf-8')
    minput = open(sys.argv[1], "r").read()
    d = PyQuery(lxml.html.fromstring(minput, parser=UTF8_PARSER))
``
