### ISSUE TITLE
.text() not exclude <!-- xxxx -->

### ISSUE THREAD

**Issue by eromoe** [gawel/pyquery#115]
http://bbs.jxzx.com.cn/forum.php?mod=viewthread&tid=687799#lastpost

`text = pq('.t_f:first').text()`

```
<!--
google_ad_client = "pub-6353198165019432";
/* 120x240, 创建于 10-7-26 */
google_ad_slot = "0566838523";
google_ad_width = 120;
google_ad_height = 240;
//--> 7月11日，市民在江苏连云港市博物馆欣赏“明宣德青花海水白龙纹扁瓶”。当日，在江苏万达2011春季艺术品拍卖会上拍出2.24亿元天价的“明宣德青花海水白龙纹扁瓶”亮相江苏连云港市博物馆，吸引众多市民一睹其“芳容”。
```

**Comment by neumond** [comment]
This can be referred to #99
I'm proposing my own implementation of text() which _does_ strip html comments.

**Comment by gawel** [comment]
And this is now the current implementation
