### ISSUE TITLE
Provide support for pypy

### ISSUE THREAD

**Issue by ruipacheco** [gawel/pyquery#121]
I'm trying to install pyquery on pypy and getting a number of errors:

```
src/lxml/lxml.etree.c:4323:15: error: no member named 'tracing' in 'struct _ts'
          tstate->tracing++;
          ~~~~~~  ^
```

I believe this comes from lxml not working well with pypy. There is a fork that apparently works with pypy:
https://github.com/amauryfa/lxml/tree/cffi

**Comment by gawel** [comment]
The last commit is 2 year old...

If you use pypy2 you can try to install lxml 3.4.4

It was working before as show this test log https://s3.amazonaws.com/archive.travis-ci.org/jobs/64783165/log.txt

Starts failing with lxml 3.5.x: https://github.com/gawel/pyquery/issues/121

**Comment by ruipacheco** [comment]
Also your log show pypy 2.5 when we're at 4, and that's a lot of bug fixes and performance improvements we'll miss. What would it take to make pyquery work with the latest or all versions of pypy?

**Comment by gawel** [comment]
pypy 4 does not exist AFAIK. The latest is 3.2.5 from the 3.x branch.

As you noticed the problem is not pyquery but lxml. You should ask on the lxml list.

But first try to install lxml 3.4.x before installing pyquery. It may work.

Nothing more I can do unless lxml itself make some progress.

**Comment by ruipacheco** [comment]
It exists:
```
$ pypy --version
Python 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Dec 01 2015, 20:51:50)
[PyPy 4.0.1 with GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
```

And as I said, there exists a build of lxml2 that works with pypy. How can I build pyquery with it?

**Comment by gawel** [comment]
Ok... But it is the python 2.7 implementation

As I said: ```pip install "lxml<3.4.999" pyquery``` works

```
% pypy
Python 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Nov 19 2015, 13:36:43)
[PyPy 4.0.1 with GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import pyquery
>>>> pyquery.PyQuery('<html/>')
[<html>]
```

**Comment by ruipacheco** [comment]
Ack.
