### ISSUE TITLE
[Question] Doesn't pyquery support Python3?

### ISSUE THREAD

**Issue by y-ich** [gawel/pyquery#124]
Hi.

I tried pyquery on Python3.
Accessing Japanese pages failed with an error

    ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Here is an example.

    from pyquery import PyQuery as pq
    a = pq(url='http://www.asahi.com')

**Comment by gawel** [comment]
That's because your webpage as a xml header:

```<?xml version="1.0" encoding="UTF-8"?>```

As a workaround you can use the following:
```
 pq(requests.get('http://www.asahi.com').content)
```

**Comment by y-ich** [comment]
Thank you!
