### ISSUE TITLE
python3.5 Installation failed

### ISSUE THREAD

**Issue by thinksaas** [gawel/pyquery#128]
python3.5 安装失败。

**Comment by gawel** [comment]
Give at least a traceback...

**Comment by thinksaas** [comment]
-> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "D:\soft\Python\Python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-bzwupi_e\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-4m4ojz6t-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-bzwupi_e\lxml\

C:\Users\Administrator>

**Comment by gawel** [comment]
The problem is related to lxml (and windows apparently). You should report to their issue tracker.

Everything is ok here: https://travis-ci.org/gawel/pyquery/jobs/116602205
