### ISSUE TITLE
PEP 396 -- Module Version Numbers

### ISSUE THREAD

**Issue by velaia** [gawel/pyquery#145]
Trying to find out which version of module is installed on my machine I had a hard time. Usually a simple 

    import module
    module.__version__

does the job.
https://www.python.org/dev/peps/pep-0396/ gives recommendations.

**Comment by asottile** [comment]
This works pretty universally:

```
$ python -c 'import pkg_resources; print(pkg_resources.get_distribution("pyquery").version)'
1.2.13
```

Note that 0396 is of the "deferred" status.
