### ISSUE TITLE
val() on nothing raises exception

### ISSUE THREAD

**Issue by levkowetz** [gawel/pyquery#147]
This returns None under 1.2.13, but raises an exception under 1.2.14.  Should it?

`
from pyquery import PyQuery

d = PyQuery('<form><input attr="foo"/></form>')
print(d.find('input[attr=bar]').val())
`

`
Traceback (most recent call last):
  File "bug.py", line 4, in <module>
    print(d.find('input[attr=bar]').val())
  File "/home/henrik/src/db/trunk/local/lib/python2.7/site-packages/pyquery/pyquery.py", line 1002, in val
    return _get_value(self[0])
IndexError: list index out of range
`

**Comment by gawel** [comment]
Nope. Introduces at #134 I guess

**Comment by gawel** [comment]
fixed

**Comment by levkowetz** [comment]
Thanks for the quick fix and release!
