### ISSUE TITLE
ImportError: cannot import name PyQuery

### ISSUE THREAD

**Issue by alxpereira** [gawel/pyquery#148]
Hey
I'm trying to import pyquery as I did hundreds on time before, and it's not working. It looks like related to the Mac OS Sierra. (module installed with pip and up-to-date)

> from pyquery import PyQuery as pq

And got an error on the namespacing

> ImportError: cannot import name PyQuery

Any idea ? Thx !

**Comment by gawel** [comment]
none

**Comment by alxpereira** [comment]
You have OSX Sierra as well ?

**Comment by gawel** [comment]
No

**Comment by alxpereira** [comment]
Found why. I was naming the file pyquery.py, so it was overriding the library... as simple as that.
Was just in a bad-luck serie yesterday..

**Comment by KeithTt** [comment]
hh...the same to you...
