### ISSUE TITLE
Pyquery abbreviates <iframe> when .html() is called

### ISSUE THREAD

**Issue by mihi-tr** [gawel/pyquery#15]
Hi,

I have trouble with parsing and displaying code like:: 

    <html>
      <head>
        <title>foo</title>
     </head>
     <body>
        <iframe src="http://www.google.com></iframe>
        <h2>google iframe</h2>
     </body>
    </html>

if i do
```python
  from pyquery import PyQuery
  pq=PyQuery(html)
  pq.html()
```

the ``<iframe>`` will appear as ``<iframe src="http://www.google.com" />`` since there is no content in the ``iframe`` tag. Thus the resulting html does not render properly in browsers. 

As a workaround .outerHtml() seems to work.

**Comment by mrnfrancesco** [comment]
I think this issue could be marked as duplicate of issue #90 and closed as dead conversation too.
However, you can find a solution in my comment at https://github.com/gawel/pyquery/issues/90#issuecomment-106840446 based on `PyQuery.html()` docstring.

**Comment by mihi-tr** [comment]
Absolutely agree.
