### ISSUE TITLE
Impossible to get an xml tag That have as name html <HR > tag 

### ISSUE THREAD

**Issue by 071792** [gawel/pyquery#163]
My xml document is like That : 

......
<product>
   .....
   <HR >
      < value > valuex </value>
   </HR >
</product>
....
And when i print my pyquery object the tag <HR > change to < hr />
How Can i tell pyquery to not use html syntaxe

**Comment by wmig** [comment]
find('H1') method cant find tags with any Upper letters ( <H1> )
but children() return it

**Comment by wmig** [comment]
its possible to use some trick - 
$._translator.lower_case_element_names = False

**Comment by gawel** [comment]
Yes, this is the trick
