### ISSUE TITLE
Docker installation issue

### ISSUE THREAD

**Issue by ipretender** [gawel/pyquery#164]
I cannot install pyquery on brand new docker image from ubuntu:latest
compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

after a few attempts to install libxml2 still have diff error messages

**Comment by gawel** [comment]
you need -dev packages for libxml2 and libxslt1 but this is because of lxml. Please refer to theyr installation page. http://lxml.de/installation.html
