### ISSUE TITLE
Get all child-nodes except the last two

### ISSUE THREAD

**Issue by Sicabol** [gawel/pyquery#169]
Hi !
I was trying to get the child-nodes of a specific node, but getting rid of the last two (used for signature and other generic information). As I don't know how many children are in this node, I've tried this:
`.myclass > *:lt(-3)`
It works well in the PHP-equivalent of pyquery (phpQuery) - even if I am a bit surprised by the "-3" instead of "-2" - but apparently it is not possible on pyquery. The result is empty.
If you have a workaround… :)
Thanks !

**Comment by gawel** [comment]
`list(pq('.myclass').items())[:-3]`
