### ISSUE TITLE
unwrap？

### ISSUE THREAD

**Issue by indiboy** [gawel/pyquery#174]
unwrap

**Comment by gawel** [comment]
Please use more than one word when opening an issue. This means nothing. Thanks.

**Comment by jstoeffler** [comment]
I am not the maintainer of this project, but it seems obvious to me that OP was referring to the [jQuery unwrap method](https://api.jquery.com/unwrap/) and its absence in pyquery. 

I'm guessing that his questions would be something like:

Is there a different method that achieves the same behavior? Or is there any plan to implement it?
