### ISSUE TITLE
<br> to newline

### ISSUE THREAD

**Issue by Soaku** [gawel/pyquery#177]
When parsing string like this:

```
<p>foo<br />
bar</p>
```

using jQuery `$("p").text()` I get:

```
test
test2
```

but here, using `pq("p").text()`, I get:

```
test test2
```

Could this be fixed? Is there any workaround for this issue?

**Comment by gawel** [comment]
Handling texts correctly is not easy. See https://github.com/gawel/pyquery/issues/99

**Comment by Soaku** [comment]
@gawel I know, wanted to analyse pq code, but failed to get any idea how to fix this.

**Comment by gawel** [comment]
Should be done with #180
