### ISSUE TITLE
Query returns the full HTML and query result

### ISSUE THREAD

**Issue by andriyor** [gawel/pyquery#184]
I have following HTML [file](https://gist.github.com/andriyor/09aa3b9aa58c7f62c999b00b52c301ad)

When i execute:
```
with open("sto.html", 'r') as f:
    contents = f.read()
    doc = pq(contents)
    [print(item.html()) for item in doc.items('div')]
```
I get following [result](https://gist.github.com/andriyor/42697776bdbe499dd93f4cbcdac67ef5) which contains full HTML and query result.
How to get only query result?

**Comment by gawel** [comment]
`[print(item.html()) for item in doc('div').items()]` ?

**Comment by andriyor** [comment]
This is equivalent to:
```
for item in doc.items('div'):
    print(item.html())
```

**Comment by andriyor** [comment]
I don't know if this is correct solution but instead of function items, I'm using find.
