### ISSUE TITLE
Performance Comparison

### ISSUE THREAD

**Issue by dorukcan** [gawel/pyquery#193]
Is there any performance measurement reports to compare this library with others like BeautifulSoup, lxml, or ElementTree?

**Comment by gawel** [comment]
pyquery use lxml, beautifulsoup can also use it. lxml is the fastest parser AFAIK

**Comment by dorukcan** [comment]
Yeah, but the overhead over initalization and iterating is not something that ignorable for scalable applications. Wouldn't a benchmark be a good promotion for pyquery library?
