### ISSUE TITLE
Why the html node name with colon will be cut from first character to colon? 

### ISSUE THREAD

**Issue by quanjinzhang** [gawel/pyquery#204]
Here is the example of the issue as follows:(I'm using python2.7 now)

```
>>> from pyquery import PyQuery as py
>>> html="<p><ac:node ac:attr='atv1' attr2='atv2'>This is demo text</ac:node></p>"
>>> p=py(html)
>>> p.html()
u'<node ac:attr="atv1" attr2="atv2">This is demo text</node>'
>>>
```

**Comment by gawel** [comment]
it's hard to deal with xml namespaces. you can either remove them with `doc.remove_namespaces()` or specify them with `PyQuery(namespaces={'ac': 'uri'}` If you choose to use namespaces then you'll have to take care of them in selectors which is very painful. Check the tests: https://github.com/gawel/pyquery/blob/master/tests/test_pyquery.py#L784

**Comment by quanjinzhang** [comment]
Thank you very much for your reply and your suggest!
