### ISSUE TITLE
.html() fails to escape initial html entities

### ISSUE THREAD

**Issue by jcushman** [gawel/pyquery#205]
The html() method returns incorrect results in some cases because it fails to escape HTML entities prior to the first tag in the inner HTML:

```
>>> PyQuery("<foo>&lt;script&gt;// uh oh&lt;/script&gt;bar<boo/></foo>").html()
'<script>// uh oh</script>bar<boo/>'
```

This has potential security implications for downstream users if processing sanitized user-controlled content.

The fix would be to html-encode `tag.text` in [the html method](https://github.com/gawel/pyquery/blob/8f2a788647c7260357e4f76fd1a19a35aa26cdee/pyquery/pyquery.py#L1068).

**Comment by gawel** [comment]
Will this be enough if you have childrens ? (also feel free to provide a PR :) )
