### ISSUE TITLE
from pyquery import PyQuery ModuleNotFoundError: No module named 'pyquery'

### ISSUE THREAD

**Issue by eabusharkh0** [gawel/pyquery#211]
Hi there,

I have a windows 10 machine.  I already installed pyquery using the command 'pip install pyquery'.  But when I try to run locust, I get the error message below.  I tried everything, I tried running the requirements.txt install and that didn't work, I still keep getting the error.  I have python 3.7 installed, can someone help?

![image](https://user-images.githubusercontent.com/57271211/88418403-201a8f00-cda9-11ea-8785-b84fa0ece221.png)

**Comment by gawel** [comment]
usualy this means that you have a pyquery.py file in your python path. please try to not use gitlab ssues to ask questions
