### ISSUE TITLE
Why PyQuery escapes "&lt;" to "<" and other HTML character entities automatically? It causes unexpected results.

### ISSUE THREAD

**Issue by ricky50575** [gawel/pyquery#218]
Example:
`html = '&lt;'`
`doc = pq(html)`
`print(doc.html())`
`print(doc.text())`
Result:
`<`
`<`

When I input a HTML string as `&lt;A Final Showdown&gt;`, it will be converted to `<A Final Showdown>` and be treated as a HTML tag!

**Comment by Darcy-C** [comment]
I found that if the element only has itself (no children) then the method `.html` and `.text` will do the same.

So I tried to modify the source code below to fix that.

turn:
https://github.com/gawel/pyquery/blob/7096042c6563cea07194a6430dea1b2dcb531b2f/pyquery/pyquery.py#L1089
to:
```python
import html as h
return h.escape(tag.text) or ''
```
Hope that will help you. 😃
