### ISSUE TITLE
remove element

### ISSUE THREAD

**Issue by initpassion** [gawel/pyquery#219]
how  to remove some html element such as:

<html>
   <textarea id="s_is_result_css" style="display:none;">
        this word need remove ①
  </textarea>

 <textarea id="s_is_result_css">
        this word where be use ②
  </textarea>
</html>

doc.find('textarea').filter(how to remove text of ①).text().remove

**Comment by gawel** [comment]
please use stackoverflow or another forum to ask questions. issues tracker are for issues...
