### ISSUE TITLE
pyquery 1.4.0 does not support Py2.7, please update the pypi

### ISSUE THREAD

**Issue by ddcatgg** [gawel/pyquery#229]
https://pypi.org/project/pyquery/1.4.0
![image](https://user-images.githubusercontent.com/8475003/152319587-28cd93ff-e019-48c7-96a2-5161632f303b.png)

![image](https://user-images.githubusercontent.com/8475003/152319693-e2e9f90e-6c58-4292-8525-0a9eac963308.png)

Thank you!

**Comment by gawel** [comment]
This is not editable on pypi and I really dont want to reupload a package. Just fix your requirements to `pyquery<1.40`. And maybe stop using python2.7... EOL  was 2 years ago...
