### ISSUE TITLE
Issue with lxml 4.7.0+

### ISSUE THREAD

**Issue by sloriot** [gawel/pyquery#237]
Hi,

First of all thanks for your lib, the CGAL open source project is using it to post-process its doxygen generated doc and it works great.

I have some issues with any version of pyquery when using lxml version 4.7.0 and after (4.6.5 is fine).

With the following simple program:
```
#!/usr/bin/env python

from pyquery import PyQuery as pq
import codecs

fname="index.html"
file_content = codecs.open(fname, 'r', encoding='utf-8')
d = pq(file_content.read(), parser="html")
file_content.close()

f = codecs.open("output.html", 'w', encoding='utf-8')
f.write(d.html())
f.close()
```

The whole page is being written twice.

I'm attaching an example page + the script
[br_pyquery.zip](https://github.com/gawel/pyquery/files/10270985/br_pyquery.zip)

Any idea what could go wrong?

**Comment by gawel** [comment]
looks like it's ok with `.html(method='html')`

I guess it can be messy when you mix html input / xml output

**Comment by sloriot** [comment]
Works! Thanks a lot
