### ISSUE TITLE
Using headers parameter fails in 2.0.0

### ISSUE THREAD

**Issue by realuser** [gawel/pyquery#246]
I'm using the headers parameter as allowed with `requests` package installed:

```
import requests
import pyquery

headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9',
    ...
} 

document = pyquery.PyQuery("https://www.example.com/", headers=headers)
```

This works in 1.4.3 but it appears the `headers` keyword doesn't work in 2.0.0 with the following error

```
Exception has occurred: ValueError
Invalid keyword arguments {'headers': {'Accept': ...
```

When I downgraded the PyQuery package back to 1.4.3 my code works again.

**Comment by gawel** [comment]
Hi, this is a known issue. Check the changelog https://github.com/gawel/pyquery/blob/master/CHANGES.rst#200-2022-12-28

**Comment by realuser** [comment]
Thanks that worked, is it possible to improve the error message? The error message made me think it was the header parameter and there was some issue with the requests integration

**Comment by gawel** [comment]
I don't think so. It will be necessary to maintains a list of all possible arguments accepted (headers, params, json, etc.) and those may vary regarding of the backend used (request/urllib). Seems a bit tricky to handle a backward incompatibility mentioned in the changelog. That's also why major version was bumped.
