### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by flisky** [gawel/pyquery#35]
python: 2.7.3
pyquery: master
cssselect: 0.8.0

``` python
from pyquery import PyQuery as pq
doc = pq([])
doc._css_to_xpath(u'a:contains("我")') 
# => u"descendant-or-self::a[contains(text(), '\u6211')]"

doc._css_to_xpath(u'a:contains("我") span')

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    doc._css_to_xpath(u'a:contains("我") span')
  File "...pyquery/pyquery.py", line 227, in _css_to_xpath
    return self._translator.css_to_xpath(selector, prefix)
  File "...cssselect-0.8-py2.7.egg/cssselect/xpath.py", line 188, in css_to_xpath
    for selector in selectors)
  File "...cssselect-0.8-py2.7.egg/cssselect/xpath.py", line 188, in <genexpr>
    for selector in selectors)
  File "...cssselect-0.8-py2.7.egg/cssselect/xpath.py", line 210, in selector_to_xpath
    return (prefix or '') + _unicode(xpath)
  File "...pyquery/cssselectpatch.py", line 35, in __unicode__
    return str(self).decode('utf-8')
  File "...pyquery/cssselectpatch.py", line 29, in __str__
    path = str(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u6211' in position 20: ordinal not in range(128)
```

**Comment by drzraf** [comment]
I'm experiencing this UnicodeError, but clearly on the pyquery side:
$ python2.7 -c 'from pyquery import PyQuery as p; print(p("é").html());'
> Ã©

$ python2.7 -c 'from pyquery import PyQuery as p; print(p("é").html());'|cat
> Traceback (most recent call last):
>  File "<string>", line 1, in <module>
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

(the only difference being piping to cat)


This incorrect encoding in the first output may be avoided (passing a lxml.html.fromstring to PyQuery).
But the fact that there is a (fatal) UnicodeEncodeError when stdout is piped is really weird.
[the setup is full utf-8]

**Comment by flisky** [comment]
@drzraf, it's clearly not pyquery's bug.

It happens on the python side, because python cannot detect the encoding for the tty.
`PYTHONIOENCODING` may help.

[YES, It's really weird before you understand this...]

**Comment by drzraf** [comment]
On Wed, Apr 15, 2015 at 11:30:03PM -0700, 尹吉峰 wrote:
> @drzraf, it's clearly not pyquery's bug.
> 
> It happens on the python side, because python cannot detect the encoding for the tty.
> `PYTHONIOENCODING` may help.

excellent! it did the trick

Then using
> reload(sys)
> sys.setdefaultencoding("utf-8")
in the script did it too.


[the fact that without any option the utf-8 character is double-encoded
in the pyquery output is another issue [python2, lxml or pyquery], but
there are workarounds]

many thanks!
