### ISSUE TITLE
Support for .make_links_absolute()

### ISSUE THREAD

**Issue by gawel** [gawel/pyquery#4]
Anonymous created an issue 2008-12-15

It would be great to have built-in support for calling .make_links_absolute() - something I find I need in order to make the most of pyquery for screen scraping.

Comments (8):

Olivier Lauzanne changed status to resolved

Sounded like a good idea. So I did it. I is available on the trunk, it will be on the next release that I will make this week. I think there are still things that could be done for making it better for screen scrapping: - make it possible to use the BeautifulSoup parser (I think it's compatible with lxml so it wouldn't be a problem) - make it possible to use auth and headers

2008-12-16

Fantastic, thanks!

2008-12-16

I have just tested this and while it works for hyperlinks it doesn't resolve other links in the document (as lxml's make_links_absolute does). I see how you've implemented it - could you expand your implementation or use lxml's native one?

http://codespeak.net/lxml/lxmlhtml.html#working-with-links provides details of its features and support.

2008-12-16
pbowyer

changed status to open

2008-12-17

Any progress on this?

2009-05-25

Found this when wondering why .make_links_absolute() doesn't make img src="" tags absolute. Please add absolute paths for img src="" as well!

Thanks, Seth

2009-07-24

Sorry I lost track of this issue. The problem with using the xml make_links_aboslute is that it will not work with the xml parser ... So I see no way of fixing it easily ...

2009-07-28

I have included this in my code, when document is loaded

```python
    from urllib import basejoin
          for attr in ( "src", "href" ):
              def abs_url(i,el):
                  if not re.match("^\s*https?://", S(el).attr[attr]):
                      S(el).attr[attr]= basejoin(self.url , S(el).attr[attr])
              S("[%s]" % attr).each(abs_url)
```

**Comment by domenkozar** [comment]
This is supported now, right?

**Comment by gawel** [comment]
right!
