### ISSUE TITLE
`.attr()` is not documented

### ISSUE THREAD

**Issue by denilsonsa** [gawel/pyquery#86]
In the official documentation: http://pyquery.readthedocs.org/en/latest/api.html

There is `removeAttr()`, but `attr()` is not listed there.

In other words, the documentation does not explain how to get or set attributes (but it explains how to remove them).

Would be nice to double-check if there are any other undocumented methods.

**Comment by twz915** [comment]
pq.doc(attr,attr_value)

Works like JQuery

**Comment by gawel** [comment]
It's documented here: http://pyquery.readthedocs.org/en/latest/attributes.html

The problem is that there's a lot of magic in that «method». I'm not sure that sphinx know how to interpret it.
