### ISSUE TITLE
textarea

### ISSUE THREAD

**Issue by israfilkara** [gawel/pyquery#94]
Hi,

I have problem.
When I try PyQuery with textarea occur problem.
For example;

from pyquery import PyQuery
> h = PyQuery(`<div>aa</div>`)
> print h
>`<div>aa</div>`

This result is OK.

> h = PyQuery(`<textarea></textarea>`)
> print h
`<textarea/>`

This result should be `<textarea></textarea>` is that right?

**Comment by israfilkara** [comment]
Above example wrong but I found error.
 I have textarea like that `<textarea class="textarea form-control" cols="40" id="id_Aciklama" name="Aciklama" rows="10"></textarea>`

When I using PyQuery result was like that 
`<textarea class="textarea form-control" cols="40" id="id_Aciklama" name="Aciklama" rows="10"/>`

Then PyQuery doesn't closed `</textarea>` tag

**Comment by gawel** [comment]
see #90
