### ISSUE TITLE
How I get the text?

### ISSUE THREAD

**Issue by zhao-ji** [gawel/pyquery#95]
>>> p.html("you know <a href='http://python.org/'>Python</a> rocks")
[<p#hello.hello>]
>>> print(p.html())
you know <a href="http://python.org/">Python</a> rocks
>>> print(p.text())
you know Python rocks

Now I can get the text "Python" by p("a").html(), so how can I get the text "rocks"?

can you help me? 
@dowski @yodalee

**Comment by gawel** [comment]
not an issue. (and I have no clue)
