### ISSUE TITLE
css selector contains not working correctly

### ISSUE THREAD

**Issue by csch0** [gawel/pyquery#98]
Tried to use this package with the following example:

```
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<table>
		<tr>
			<td>r1 / c1</td>
			<td>r1 / c2</td>
		</tr>
		<tr>
			<td>r2 / c1</td>
			<td>r2 / c2</td>
		</tr>
	</table>
</body>
</html>
```

jQuery $('table:contains("r1")') will clearly return the whole table. pyquery instead returns nothing with q('table:contains("r1")')

am I missing something??

**Comment by gawel** [comment]
was a bug
